- hosts: all
  become: yes
  become_method: sudo
  vars_files:
    - vars.yml
  vars:
    ansible_user: "{{ sshUsername }}"
    ansible_ssh_private_key_file: "{{ keyRoot }}"
    ansible_port: "{{ ansiblePort }}"
  tasks:
  - name: "get docker info"
    shell: docker info
    register: docker_info
    changed_when: false


#Initiate the Swarm
#  https://caylent.com/manage-docker-swarm-using-ansible/
- hosts: docker-manager-first
  become: yes
  become_method: sudo
  vars_files:
    - vars.yml
  vars:
    ansible_user: "{{ sshUsername }}"
    ansible_ssh_private_key_file: "{{ keyRoot }}"
    ansible_port: "{{ ansiblePort }}"
  tasks:
    # The following tasks initiate a Docker Swarm and then save the master and worker tokens so we can add more hosts to the cluster
  - name: "create primary swarm manager"
    shell: docker swarm init --advertise-addr {{ ansible_eth0['ipv4']['address'] }}
    when: "docker_info.stdout.find('Swarm: inactive') != -1"

#  - name: "get docker swarm manager token"
#    shell: docker swarm join-token -q manager
#    register: manager_token
#
#  - name: "get docker swarm worker token"
#    shell: docker swarm join-token -q worker
#    register: worker_token


